apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  namespace: mumk8s
  labels:
    app: rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
        - name: rabbitmq-consumer
          image: ${ZOT_HOST}/mumk8s/go-consumer:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mumk8s-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
