apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-grpc-server
  namespace: mumk8s
  labels:
    app: go-grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-grpc-server
  template:
    metadata:
      labels:
        app: go-grpc-server
    spec:
      containers:
        - name: go-grpc-server
          image: ${ZOT_HOST}/mumk8s/go-grpc-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: mumk8s-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 10
            periodSeconds: 20
