apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: mumk8s
  labels:
    app: rust-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
        - name: rust-api
          image: ${ZOT_HOST}/mumk8s/rust-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mumk8s-config
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /grpc-201114493
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /grpc-201114493
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5
