apiVersion: v1
kind: Service
metadata:
  name: go-grpc-server-svc
  namespace: mumk8s
  labels:
    app: go-grpc-server
spec:
  selector:
    app: go-grpc-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
