apiVersion: v1
kind: Service
metadata:
  name: go-grpc-client-svc
  namespace: mumk8s
  labels:
    app: go-grpc-client
spec:
  selector:
    app: go-grpc-client
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
